### ISSUE TITLE
[FeatureRequest] Smileys and alignment

### ISSUE THREAD

**Issue by Leobaillard** [codeconsortium/CCDNComponentBBCodeBundle#2]
Would it be possible to handle smileys and alignment ?

If not right away, could you give hints on how to do this properly with the Bundle ?

Many thanks in advance.

**Comment by codeconsortium** [comment]
Smileys are definitly planned to be implemented though it could be a matter of weeks. Alignment could also be done easily enough. 

The tags are defined in the file BBCodeBundle\Engine\BBCodeEngine.php within the constructor (starting line 62). Simply add the tags for the alignment the same as the more simpler tags like 'bold'/'underline'/'italics' etc, and the html counterpart is just a simple <center> etc tags.

centre tag e.g:

```
        array(  'symbol_lexeme' => 'center',
                'symbol_token' => array('/(\[center\])/', '/(\[\/center\])/'),
                'symbol_html' => array('<center>', '</center>'),
        ),
```

As for smileys, not entirely sure how they will be implemented yet, but work will begin on adding them within the next couple of weeks.

**Comment by Leobaillard** [comment]
Also it would be great to have xHTML capabilities :)

**Comment by codeconsortium** [comment]
@Leobaillard please clarify on what you mean by 'xHTML capabilities' ?

If by that you mean you would like it to accept/ignore selectively html tags then that would not be possible, all HTML tags are escaped, only BB Tags are parsed. If you meant something else please clarify further.

**Comment by codeconsortium** [comment]
Smileys have been added a while back now. If you wish to add alignment however you will have to add them in the lexemeTable.php file.
